@URL=http://localhost:8080/transaction


### TRANSFER
POST {{URL}}/transfer
Content-Type: application/json

{
    "sourceAccountNumber": 123456,
    "receiverAccountNumber": 11111,
    "amount": 5000
}

### WITHDRAW
POST {{URL}}/withdraw
Content-Type: application/json

{
    "sourceAccountNumber": 12346,
    "amount": 1000
}



### DEPOSIT
POST {{URL}}/deposit
Content-Type: application/json

{
    "receiverAccountNumber": 11111,
    "amount": 200000
}
